// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActivityBox: typeof import('./components/templates/ActivityBox.vue')['default']
    ActivityType: typeof import('./components/molecules/ActivityType.vue')['default']
    AppHeader: typeof import('./components/organisms/AppHeader.vue')['default']
    AppShell: typeof import('./components/templates/AppShell.vue')['default']
    AppSide: typeof import('./components/organisms/AppSide.vue')['default']
    AppSiteItem: typeof import('./components/molecules/AppSiteItem.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CycleForm: typeof import('./components/organisms/CycleForm.vue')['default']
    DashboardTemplate: typeof import('./components/templates/DashboardTemplate.vue')['default']
    EventForm: typeof import('./components/organisms/EventForm.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormField: typeof import('./components/molecules/FormField.vue')['default']
    HabitItem: typeof import('./components/organisms/HabitItem.vue')['default']
    HabitsTemplate: typeof import('./components/templates/HabitsTemplate.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
